FROM mcr.microsoft.com/playwright:v1.44.0-jammy

WORKDIR /app/frontend
COPY package*.json .
RUN npm install

RUN npx playwright install --with-deps

COPY . .

ENV VITE_API_URL=http://localhost:3000
ENV VITE_WS_URL=ws://localhost:3000/cable
