version: '3.8'

services:
  api:
    image: artamira-api # Use the image built by the main docker-compose.yml
    volumes:
      - ./api:/rails
      - /rails/tmp
      - test_rails_storage:/rails/storage # テスト専用のストレージボリューム
    ports:
      - "3001:3000" # テスト環境用のAPIポート
    command: sh -c "bundle exec rails db:reset && echo \"--- Running db:seed ---\" && bundle exec rails db:seed && echo \"--- db:seed finished ---\" && /rails/bin/docker-entrypoint rails server -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: your_master_key_here

  frontend:
    image: artamira-frontend # Use the image built by the main docker-compose.yml
    volumes:
      - ./frontend:/app
    ports:
      - "5174:5173" # テスト環境用のフロントエンドポート
    depends_on:
      api:
        condition: service_started
    command: npm run dev
    environment: # フロントエンドがテストAPIに接続するように設定
      VITE_API_URL: http://localhost:3001 # ホストからアクセス可能なAPIポート
      VITE_WS_URL: ws://localhost:3001/cable # ホストからアクセス可能なWSポート

volumes:
  test_rails_storage: # 新しいテスト専用のボリュームを定義
